# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ciclos',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'contenidos',
            },
        ),
        migrations.CreateModel(
            name='CriterioDeEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('letra', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'criterios_de_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('codigo_junta', models.IntegerField()),
                ('horas_anuales', models.IntegerField()),
                ('horas_semanales', models.IntegerField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='PuntoDeContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Contenido')),
            ],
            options={
                'db_table': 'puntos_de_contenidos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
            ],
            options={
                'db_table': 'resultados_de_aprendizaje',
            },
        ),
        migrations.AddField(
            model_name='criteriodeevaluacion',
            name='resultado_de_aprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.ResultadoDeAprendizaje'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo'),
        ),
    ]
