# Generated by Django 3.0.4 on 2020-03-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('abreviatura', models.CharField(max_length=10)),
                ('nivel_profesional', models.IntegerField()),
            ],
            options={
                'db_table': 'ciclos',
            },
        ),
        migrations.CreateModel(
            name='CicloTieneCualificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_completa', models.BooleanField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'verbose_name_plural': 'Ciclo y cualificaciones',
                'db_table': 'ciclo_tiene_cualificacion',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'contenidos',
            },
        ),
        migrations.CreateModel(
            name='CualificacionProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('real_decreto', models.CharField(max_length=240)),
                ('ciclo', models.ManyToManyField(through='gestionbd.CicloTieneCualificacion', to='gestionbd.Ciclo')),
            ],
            options={
                'verbose_name_plural': 'Cualificaciones profesionales',
                'db_table': 'cualificaciones_profesionales',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_curso', models.IntegerField()),
                ('nombre_curso', models.CharField(max_length=20)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='EspecialidadProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('PS', 'Prof. Secundaria'), ('PT', 'Prof. Tecnico')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidesprofesorado',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('codigo_junta', models.CharField(max_length=5)),
                ('horas_anuales', models.IntegerField()),
                ('horas_semanales', models.IntegerField()),
                ('especialidad', models.CharField(max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Curso')),
            ],
            options={
                'verbose_name_plural': 'Modulos',
                'db_table': 'modulos',
                'ordering': ['nombre', 'curso'],
            },
        ),
        migrations.CreateModel(
            name='UnidadDeCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('cualificacion', models.ManyToManyField(to='gestionbd.CualificacionProfesional')),
            ],
            options={
                'verbose_name_plural': 'Unidades de competencia',
                'db_table': 'unidades_de_competencia',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
            ],
            options={
                'verbose_name_plural': 'Resultados de aprendizaje',
                'db_table': 'resultados_de_aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='PuntoDeContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('num_orden', models.IntegerField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Contenido')),
            ],
            options={
                'verbose_name_plural': 'Puntos de contenido',
                'db_table': 'puntos_de_contenidos',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('horas_minimas', models.IntegerField()),
                ('num_posicion', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.EspecialidadProfesor')),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=2048)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'verbose_name_plural': 'Objetivos Generales de Ciclo',
                'db_table': 'objetivosgenerales',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=15)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Curso')),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='CriterioDeEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('letra', models.CharField(max_length=2)),
                ('resultado_de_aprendizaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.ResultadoDeAprendizaje')),
            ],
            options={
                'verbose_name_plural': 'Criterios de evaluacion',
                'db_table': 'criterios_de_evaluacion',
            },
        ),
        migrations.AddField(
            model_name='contenido',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo'),
        ),
        migrations.CreateModel(
            name='CompetenciaGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=512)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'verbose_name_plural': 'Competencias Generales',
                'db_table': 'competenciasgenerales',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'verbose_name_plural': 'Competencias',
                'db_table': 'competencias',
            },
        ),
        migrations.AddField(
            model_name='ciclotienecualificacion',
            name='cualificacion_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.CualificacionProfesional'),
        ),
    ]
