# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('abreviatura', models.CharField(max_length=10)),
                ('nivel_profesional', models.IntegerField()),
            ],
            options={
                'db_table': 'ciclos',
            },
        ),
        migrations.CreateModel(
            name='CicloTieneCualificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_completa', models.BooleanField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'db_table': 'ciclo_tiene_cualificacion',
                'verbose_name_plural': 'Ciclo y cualificaciones',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'db_table': 'competencias',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'contenidos',
            },
        ),
        migrations.CreateModel(
            name='CriterioDeEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('letra', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'criterios_de_evaluacion',
                'verbose_name_plural': 'Criterios de evaluacion',
            },
        ),
        migrations.CreateModel(
            name='CualificacionProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('completa', models.BooleanField()),
                ('real_decreto', models.CharField(max_length=240)),
                ('ciclo', models.ManyToManyField(through='gestionbd.CicloTieneCualificacion', to='gestionbd.Ciclo')),
            ],
            options={
                'db_table': 'cualificaciones_profesionales',
                'verbose_name_plural': 'Cualificaciones profesionales',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_curso', models.IntegerField()),
                ('nombre_curso', models.CharField(max_length=20)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=15)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Curso')),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('codigo_junta', models.IntegerField()),
                ('horas_anuales', models.IntegerField()),
                ('horas_semanales', models.IntegerField()),
                ('especialidad', models.CharField(max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Curso')),
            ],
            options={
                'db_table': 'modulos',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('horas_minimas', models.IntegerField()),
                ('num_posicion', models.IntegerField()),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='PuntoDeContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('num_orden', models.IntegerField()),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Contenido')),
            ],
            options={
                'db_table': 'puntos_de_contenidos',
                'verbose_name_plural': 'Puntos de contenido',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
            ],
            options={
                'db_table': 'resultados_de_aprendizaje',
                'verbose_name_plural': 'Resultados de aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('cualificacion', models.ManyToManyField(to='gestionbd.CualificacionProfesional')),
            ],
            options={
                'db_table': 'unidades_de_competencia',
                'verbose_name_plural': 'Unidades de competencia',
            },
        ),
        migrations.AddField(
            model_name='criteriodeevaluacion',
            name='resultado_de_aprendizaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.ResultadoDeAprendizaje'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo'),
        ),
        migrations.AddField(
            model_name='ciclotienecualificacion',
            name='cualificacion_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.CualificacionProfesional'),
        ),
    ]
