# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CualificacionProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('ciclo', models.ManyToManyField(to='gestionbd.Ciclo')),
            ],
            options={
                'verbose_name_plural': 'Cualificaciones profesionales',
                'db_table': 'cualificaciones_profesionales',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=240)),
                ('cualificacion', models.ManyToManyField(to='gestionbd.CualificacionProfesional')),
            ],
            options={
                'verbose_name_plural': 'Unidades de competencia',
                'db_table': 'unidades_de_competencia',
            },
        ),
        migrations.AlterModelOptions(
            name='competencia',
            options={'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='criteriodeevaluacion',
            options={'verbose_name_plural': 'Criterios de evaluacion'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='puntodecontenido',
            options={'verbose_name_plural': 'Puntos de contenido'},
        ),
        migrations.AlterModelOptions(
            name='resultadodeaprendizaje',
            options={'verbose_name_plural': 'Resultados de aprendizaje'},
        ),
        migrations.AlterModelTable(
            name='competencia',
            table='competencias',
        ),
    ]
