# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0002_puntodecontenido_num_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulo',
            name='especialidad',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
