# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0002_puntodecontenido_num_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulo',
            name='especialidad',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
