# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0003_auto_20160807_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_curso', models.IntegerField()),
                ('nombre_curso', models.CharField(max_length=20)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='ciclo',
        ),
        migrations.AlterField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Curso'),
        ),
    ]
