# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0003_especialidadprofesor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidadprofesor',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='especialidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionbd.EspecialidadProfesor'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='especialidadprofesor',
            table='especialidesprofesorado',
        ),
    ]
