# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0004_auto_20161009_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2)),
                ('texto', models.CharField(max_length=2048)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'db_table': 'objetivosgenerales',
                'verbose_name_plural': 'Objetivos Generales de Ciclo',
            },
        ),
    ]
