# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0004_auto_20160807_1158'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='cursos',
        ),
    ]
