# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0005_objetivogeneral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['nombre', 'curso'], 'verbose_name_plural': 'Modulos'},
        ),
    ]
