# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0005_auto_20160807_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=15)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Curso')),
            ],
        ),
    ]
