# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0006_auto_20161010_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=512)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Ciclo')),
            ],
            options={
                'verbose_name_plural': 'Competencias Generales',
                'db_table': 'competenciasgenerales',
            },
        ),
    ]
