# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0006_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reparto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'repartos',
            },
        ),
        migrations.AlterModelTable(
            name='grupo',
            table='grupos',
        ),
    ]
