# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0007_competenciageneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='codigo_junta',
            field=models.CharField(max_length=5),
        ),
    ]
