# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0007_auto_20160807_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='max_horas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
