# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0008_profesor_max_horas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='max_horas',
            new_name='horas_minimas',
        ),
    ]
