# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0009_auto_20160807_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='curso',
        ),
        migrations.AddField(
            model_name='modulo',
            name='grupo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Grupo'),
            preserve_default=False,
        ),
    ]
