# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0011_auto_20160830_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='nivel_profesional',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
