# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0012_ciclo_nivel_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='num_posicion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
