# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0013_profesor_num_posicion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reparto',
        ),
    ]
