# Generated by Django 4.1 on 2022-10-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=180)),
            ],
            options={
                'verbose_name_plural': 'Calificadores',
                'db_table': 'calificadores',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='InstrumentoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Instrumentos de evaluacion',
                'db_table': 'instrumentos_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Interviene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_criterio_minimo', models.BooleanField()),
                ('ponderacion', models.IntegerField()),
                ('calificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programaciones.calificador')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.criteriodeevaluacion')),
            ],
            options={
                'verbose_name_plural': 'Criterios en UT',
                'db_table': 'criterios_unidades_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=240)),
                ('modulo', models.ManyToManyField(to='gestionbd.modulo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.profesor')),
            ],
            options={
                'verbose_name_plural': 'Programaciones',
                'db_table': 'programaciones',
            },
        ),
        migrations.CreateModel(
            name='PuntoMetodologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=4096)),
            ],
            options={
                'verbose_name_plural': 'Puntos de Metodologia',
                'db_table': 'puntos_de_metodologia',
            },
        ),
        migrations.CreateModel(
            name='RecursoDidactico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Recursos didacticos',
                'db_table': 'recursos_didacticos',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=180)),
                ('sesiones', models.IntegerField()),
                ('contenidos', models.ManyToManyField(to='gestionbd.contenido')),
                ('criterios', models.ManyToManyField(through='programaciones.Interviene', to='gestionbd.criteriodeevaluacion')),
                ('evaluaciones', models.ManyToManyField(to='programaciones.evaluacion')),
                ('instrumentos', models.ManyToManyField(to='programaciones.instrumentoevaluacion')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programaciones.programacion')),
                ('puntos_contenido', models.ManyToManyField(to='gestionbd.puntodecontenido')),
                ('puntos_metodologia', models.ManyToManyField(to='programaciones.puntometodologico')),
                ('recursos', models.ManyToManyField(to='programaciones.recursodidactico')),
                ('resultado_aprendizaje', models.ManyToManyField(to='gestionbd.resultadodeaprendizaje')),
            ],
            options={
                'verbose_name_plural': 'Unidades de Trabajo',
                'db_table': 'unidades_de_trabajo',
            },
        ),
        migrations.CreateModel(
            name='ObjetivosModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.modulo')),
                ('objetivos', models.ManyToManyField(to='gestionbd.objetivogeneral')),
            ],
            options={
                'verbose_name_plural': 'Objetivos de modulo',
                'db_table': 'objetivosmodulo',
            },
        ),
        migrations.AddField(
            model_name='interviene',
            name='unidad_de_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programaciones.unidaddetrabajo'),
        ),
        migrations.CreateModel(
            name='CompetenciasModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencias', models.ManyToManyField(to='gestionbd.competencia')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.modulo')),
            ],
            options={
                'verbose_name_plural': 'Competencias del modulo',
                'db_table': 'competenciasmodulo',
            },
        ),
    ]
