# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'evaluaciones',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Interviene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_criterio_minimo', models.BooleanField()),
                ('ponderacion', models.IntegerField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.CriterioDeEvaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='MecanismoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'mecanismosevaluacion',
                'verbose_name_plural': 'Mecanismos de evaluacion',
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'procedimientosevaluacion',
                'verbose_name_plural': 'Procedimientos de evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ManyToManyField(to='gestionbd.Modulo')),
            ],
            options={
                'db_table': 'programaciones',
                'verbose_name_plural': 'Programaciones',
            },
        ),
        migrations.CreateModel(
            name='PuntoMetodologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'puntos_de_metodologia',
                'verbose_name_plural': 'Puntos de Metodologia',
            },
        ),
        migrations.CreateModel(
            name='RecursoDidactico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'recursos_didacticos',
                'verbose_name_plural': 'Recursos didacticos',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=180)),
                ('sesiones', models.IntegerField()),
                ('criterios', models.ManyToManyField(through='programaciones.Interviene', to='gestionbd.CriterioDeEvaluacion')),
                ('evaluaciones', models.ManyToManyField(to='programaciones.Evaluacion')),
                ('mecanismos', models.ManyToManyField(to='programaciones.MecanismoEvaluacion')),
                ('procedimientos', models.ManyToManyField(to='programaciones.ProcedimientoEvaluacion')),
                ('puntos_metodologia', models.ManyToManyField(to='programaciones.PuntoMetodologico')),
                ('recursos', models.ManyToManyField(to='programaciones.RecursoDidactico')),
            ],
            options={
                'db_table': 'unidades_de_trabajo',
                'verbose_name_plural': 'Unidades de Trabajo',
            },
        ),
        migrations.AddField(
            model_name='programacion',
            name='unidades',
            field=models.ManyToManyField(to='programaciones.UnidadDeTrabajo'),
        ),
        migrations.AddField(
            model_name='interviene',
            name='unidad_de_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programaciones.UnidadDeTrabajo'),
        ),
    ]
