# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoMetodologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'puntos_de_metodologia',
            },
        ),
        migrations.AlterModelTable(
            name='unidaddetrabajo',
            table='unidades_de_trabajo',
        ),
        migrations.AddField(
            model_name='puntometodologico',
            name='unidades',
            field=models.ManyToManyField(to='programaciones.UnidadDeTrabajo'),
        ),
    ]
