# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='nombre',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
    ]
