# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0002_auto_20160923_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntometodologico',
            name='unidades',
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='puntos_metodologia',
            field=models.ManyToManyField(to='programaciones.PuntoMetodologico'),
        ),
    ]
