# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0002_programacion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=180)),
            ],
            options={
                'verbose_name_plural': 'Calificadores',
                'db_table': 'calificadores',
            },
        ),
        migrations.RenameModel(
            old_name='MecanismoEvaluacion',
            new_name='InstrumentoEvaluacion',
        ),
        migrations.AlterModelOptions(
            name='instrumentoevaluacion',
            options={'verbose_name_plural': 'Instrumentos de evaluacion'},
        ),
        migrations.AlterModelOptions(
            name='interviene',
            options={'verbose_name_plural': 'Criterios en UT'},
        ),
        migrations.RenameField(
            model_name='unidaddetrabajo',
            old_name='mecanismos',
            new_name='instrumentos',
        ),
        migrations.AlterModelTable(
            name='instrumentoevaluacion',
            table='instrumentos_evaluacion',
        ),
        migrations.AlterModelTable(
            name='interviene',
            table='criterios_unidades_trabajo',
        ),
        migrations.AddField(
            model_name='interviene',
            name='calificador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='programaciones.Calificador'),
            preserve_default=False,
        ),
    ]
