# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0003_auto_20160923_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'evaluaciones',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.AlterModelOptions(
            name='puntometodologico',
            options={'verbose_name_plural': 'Puntos de Metodologia'},
        ),
        migrations.AlterModelOptions(
            name='unidaddetrabajo',
            options={'verbose_name_plural': 'Unidades de Trabajo'},
        ),
    ]
