# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0002_remove_cualificacionprofesional_completa'),
        ('programaciones', '0003_auto_20161009_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='profesor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Profesor'),
            preserve_default=False,
        ),
    ]
