# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0004_programacion_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidaddetrabajo',
            name='procedimientos',
        ),
        migrations.DeleteModel(
            name='ProcedimientoEvaluacion',
        ),
    ]
