# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0014_delete_reparto'),
        ('programaciones', '0004_auto_20160923_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ManyToManyField(to='gestionbd.Modulo')),
            ],
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='evaluaciones',
            field=models.ManyToManyField(to='programaciones.Evaluacion'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='unidades',
            field=models.ManyToManyField(to='programaciones.UnidadDeTrabajo'),
        ),
    ]
