# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0005_auto_20160923_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoDidactico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'recursos_didacticos',
                'verbose_name_plural': 'Recursos didacticos',
            },
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='recursos',
            field=models.ManyToManyField(to='programaciones.RecursoDidactico'),
        ),
    ]
