# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0005_auto_20161009_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='unidades',
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='programacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='programaciones.Programacion'),
            preserve_default=False,
        ),
    ]
