# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0005_objetivogeneral'),
        ('programaciones', '0006_auto_20161009_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='objetivos',
            field=models.ManyToManyField(to='gestionbd.ObjetivoGeneral'),
        ),
    ]
