# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0006_auto_20160923_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacion',
            options={'verbose_name_plural': 'Programaciones'},
        ),
        migrations.AlterModelTable(
            name='programacion',
            table='programaciones',
        ),
    ]
