# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0006_auto_20161010_0740'),
        ('programaciones', '0007_programacion_objetivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionObjetivosModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
                ('objetivos', models.ManyToManyField(to='gestionbd.ObjetivoGeneral')),
            ],
            options={
                'verbose_name_plural': 'ProgramacionObjetivosModulo',
                'db_table': 'programacionobjetivosmodulo',
            },
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='objetivos',
        ),
        migrations.AddField(
            model_name='programacionobjetivosmodulo',
            name='programacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programaciones.Programacion'),
        ),
    ]
