# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0007_auto_20160923_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='MecanismoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Mecanismos de evaluacion',
                'db_table': 'mecanismosevaluacion',
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Procedimientos de evaluacion',
                'db_table': 'procedimientosevaluacion',
            },
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='mecanismos',
            field=models.ManyToManyField(to='programaciones.MecanismoEvaluacion'),
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='procedimientos',
            field=models.ManyToManyField(to='programaciones.ProcedimientoEvaluacion'),
        ),
    ]
