# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0006_auto_20161010_0740'),
        ('programaciones', '0008_auto_20161010_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionobjetivosmodulo',
            name='modulo',
        ),
        migrations.AddField(
            model_name='programacion',
            name='modulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo'),
            preserve_default=False,
        ),
    ]
