# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0014_delete_reparto'),
        ('programaciones', '0008_auto_20160923_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_criterio_minimo', models.BooleanField()),
                ('ponderacion', models.IntegerField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.CriterioDeEvaluacion')),
                ('unidad_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programaciones.UnidadDeTrabajo')),
            ],
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='criterios',
            field=models.ManyToManyField(through='programaciones.Interviene', to='gestionbd.CriterioDeEvaluacion'),
        ),
    ]
