# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0007_competenciageneral'),
        ('programaciones', '0010_auto_20161010_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciasModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
                ('objetivos', models.ManyToManyField(to='gestionbd.Competencia')),
            ],
            options={
                'verbose_name_plural': 'Competencias del modulo',
                'db_table': 'competenciasmodulo',
            },
        ),
    ]
