# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programaciones', '0011_competenciasmodulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competenciasmodulo',
            old_name='objetivos',
            new_name='competencias',
        ),
    ]
