# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0007_competenciageneral'),
        ('programaciones', '0012_auto_20161011_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='puntos_contenido',
            field=models.ManyToManyField(to='gestionbd.PuntoDeContenido'),
        ),
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='resultado_aprendizaje',
            field=models.ManyToManyField(to='gestionbd.ResultadoDeAprendizaje'),
        ),
    ]
