# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0007_competenciageneral'),
        ('programaciones', '0013_auto_20161022_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidaddetrabajo',
            name='contenidos',
            field=models.ManyToManyField(to='gestionbd.Contenido'),
        ),
    ]
