# Generated by Django 4.1 on 2022-10-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEnReparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignable', models.BooleanField()),
                ('grupo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.grupo')),
                ('modulo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.modulo')),
            ],
            options={
                'ordering': ['modulo_asociado__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.moduloenreparto')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.profesor')),
            ],
            options={
                'ordering': ['modulo'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.moduloenreparto')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.profesor')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.reparto')),
            ],
        ),
    ]
