# Generated by Django 3.0.4 on 2020-03-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEnReparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignable', models.BooleanField()),
                ('grupo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Grupo')),
                ('modulo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
            ],
            options={
                'ordering': ['modulo_asociado__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.ModuloEnReparto')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Profesor')),
            ],
            options={
                'ordering': ['modulo'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.ModuloEnReparto')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Profesor')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.Reparto')),
            ],
        ),
    ]
