# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='reparto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reparto.Reparto'),
            preserve_default=False,
        ),
    ]
