# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0007_competenciageneral'),
        ('reparto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Profesor')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.Reparto')),
            ],
        ),
        migrations.RemoveField(
            model_name='moduloasignado',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='moduloasignado',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='moduloasignado',
            name='reparto',
        ),
        migrations.RemoveField(
            model_name='moduloporasignar',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='moduloporasignar',
            name='reparto',
        ),
        migrations.DeleteModel(
            name='ModuloAsignado',
        ),
        migrations.DeleteModel(
            name='ModuloEnReparto',
        ),
        migrations.DeleteModel(
            name='ModuloPorAsignar',
        ),
    ]
