# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0011_auto_20160830_1704'),
        ('reparto', '0002_asignacion_reparto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloParaRepartir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reparto.Profesor')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.Reparto')),
            ],
        ),
    ]
