# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0002_auto_20170413_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparto',
            name='id',
        ),
        migrations.AlterField(
            model_name='reparto',
            name='nombre',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
