# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0003_modulopararepartir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reparto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
