# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0007_competenciageneral'),
        ('reparto', '0003_auto_20170415_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEnReparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Grupo')),
                ('modulo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
            ],
        ),
    ]
