# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0004_auto_20160907_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='posicion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
