# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0004_moduloenreparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.ModuloEnReparto'),
        ),
    ]
