# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0005_profesor_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Profesor'),
        ),
        migrations.AlterField(
            model_name='modulopararepartir',
            name='asignado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Profesor'),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
