# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0013_profesor_num_posicion'),
        ('reparto', '0006_auto_20160908_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Profesor')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.Reparto')),
            ],
        ),
        migrations.CreateModel(
            name='ModuloPorAsignar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Modulo')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.Reparto')),
            ],
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='reparto',
        ),
        migrations.RemoveField(
            model_name='modulopararepartir',
            name='asignado',
        ),
        migrations.RemoveField(
            model_name='modulopararepartir',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='modulopararepartir',
            name='reparto',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='ModuloParaRepartir',
        ),
    ]
