# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0006_preferenciaprofesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaprofesor',
            name='prioridad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
