# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionbd', '0013_profesor_num_posicion'),
        ('reparto', '0007_auto_20160908_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduloasignado',
            name='id',
        ),
        migrations.RemoveField(
            model_name='moduloasignado',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='moduloporasignar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='moduloporasignar',
            name='modulo',
        ),
        migrations.AddField(
            model_name='moduloasignado',
            name='modulo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionbd.Modulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduloporasignar',
            name='modulo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestionbd.Modulo'),
            preserve_default=False,
        ),
    ]
