# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0008_auto_20160908_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEnReparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('grupo', models.CharField(max_length=20)),
                ('horas_semanales', models.IntegerField()),
                ('especialidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='moduloasignado',
            name='modulo_ptr',
        ),
        migrations.RemoveField(
            model_name='moduloporasignar',
            name='modulo_ptr',
        ),
        migrations.AddField(
            model_name='moduloasignado',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduloporasignar',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduloasignado',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparto.ModuloEnReparto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moduloporasignar',
            name='modulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reparto.ModuloEnReparto'),
            preserve_default=False,
        ),
    ]
