# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0008_auto_20170424_1646'),
        ('reparto', '0008_auto_20170425_0856'),
    ]

    operations = [
    ]
