# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0009_merge_20170425_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduloenreparto',
            name='asignable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
