# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0010_moduloenreparto_asignable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduloenreparto',
            options={'ordering': ['modulo_asociado__nombre']},
        ),
    ]
