# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionbd', '0007_competenciageneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido1', models.CharField(max_length=60)),
                ('apellido2', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('tutor1', models.CharField(max_length=80)),
                ('tutor2', models.CharField(max_length=80)),
                ('vive_solo', models.BooleanField()),
                ('calle_notas', models.CharField(max_length=80)),
                ('cp_notas', models.IntegerField()),
                ('poblacion_notas', models.CharField(max_length=40)),
                ('tlf_alumno', models.CharField(max_length=14)),
                ('tlf_urgencia', models.CharField(max_length=14)),
                ('foto', models.FileField(upload_to='')),
                ('repetidor', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.Curso')),
            ],
        ),
    ]
