# Generated by Django 4.1 on 2022-10-08 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('apellido1', models.CharField(max_length=60)),
                ('apellido2', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='En el DNI/NIE por favor, usa solo numeros y mayúsculas. Ni guiones, ni puntos ni cualquier otro símbolo, gracias', regex='([0-9]{7,8}[A-Z])|([A-Z][0-9]{7,8})')])),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('tutor1', models.CharField(max_length=80)),
                ('tutor2', models.CharField(max_length=80)),
                ('independizado', models.CharField(choices=[('EMANCIPADO', 'Estoy independizado'), ('NO_EMANCIPADO', 'No estoy independizado')], max_length=100)),
                ('direccion_notas', models.CharField(max_length=80)),
                ('cp_notas', models.IntegerField(default=13001)),
                ('poblacion_notas', models.CharField(default='Ciudad Real', max_length=40)),
                ('tlf_alumno', models.CharField(max_length=14)),
                ('tlf_urgencia', models.CharField(max_length=14)),
                ('repetidor', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion', models.CharField(choices=[('APRO', 'Lo tengo aprobado de años anteriores'), ('CONV', 'Lo tengo convalidado'), ('PEND CONV.', 'Quiero pedir que me lo convaliden'), ('MATRICULADO', 'Tengo que cursarlo')], default='MATRICULADO', max_length=20)),
                ('convocatorias_restantes', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.alumno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionbd.modulo')),
            ],
        ),
    ]
