# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 13:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0002_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='vive_solo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='independizado',
            field=models.CharField(choices=[('EMANCIPADO', 'Estoy independizado'), ('CON_PADRES_EN_CR', 'Vivo con padre/madre/familia en CR'), ('CON_PADRES_FUERA_DE_CR', 'Vivo en CR, pero dependo de mi familia')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='convocatorias_restantes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='situacion',
            field=models.CharField(choices=[('APRO', 'Lo tengo aprobado de años anteriores'), ('CONV', 'Lo tengo convalidado'), ('PEND CONV.', 'Quiero pedir que me lo convaliden'), ('MATRICULADO', 'Tengo que cursarlo')], default='EMANCIPADO', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cp_notas',
            field=models.IntegerField(default=13001),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='poblacion_notas',
            field=models.CharField(default='Ciudad Real', max_length=40),
        ),
    ]
