# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0003_auto_20170902_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='independizado',
            field=models.CharField(choices=[('EMANCIPADO', 'Estoy independizado'), ('NO_EMANCIPADO', 'No estoy independizado')], max_length=100),
        ),
    ]
