# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0004_auto_20170902_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
