# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0005_alumno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
