# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0006_auto_20170903_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='calle_notas',
            new_name='direccion_notas',
        ),
    ]
