# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0008_auto_20170903_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='convocatorias_restantes',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='situacion',
            field=models.CharField(choices=[('APRO', 'Lo tengo aprobado de años anteriores'), ('CONV', 'Lo tengo convalidado'), ('PEND CONV.', 'Quiero pedir que me lo convaliden'), ('MATRICULADO', 'Tengo que cursarlo')], default='MATRICULADO', max_length=10),
        ),
    ]
