# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0009_auto_20170918_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='foto',
        ),
    ]
